### ISSUE TITLE
Status 500

### ISSUE THREAD

**Issue by rashmijhunjhunwala** [Crazyprogrammer1/razorpay-payments#3]
Getting an HttpErrorResponse status 500 on sending a POST request to the createOrder function

**Comment by saurabh29july** [comment]
I get the same

{ statusCode: undefined, error: undefined }

**Comment by rashmijhunjhunwala** [comment]
You will have to upgrade to the firebase blaze plan, As we are calling an external API, which is not allowed in the spark plan.
